mirumee/nimara-ecommerce

apps/storefront/src/components/shopping-bag/components/line.tsx

I want to merge this change because it improves cart qty field by displaying drawer with selection on mobiles.

feat: Improve cart qty field

---

apps/storefront/src/app/[locale]/(main)/products/[slug]/components/variant-selector.tsx

I want to merge this change because it fixes product variants which disappear when user selects one of them

fix: Fix disappearing product variants while clicking

---

apps/storefront/src/app/[locale]/(main)/_components/hero-banner.tsx
apps/storefront/src/app/[locale]/(main)/_components/products-grid.tsx
packages/infrastructure/src/public/butter-cms/cms-menu/infrastructure/cms-menu-get-infra.ts
packages/infrastructure/src/public/butter-cms/cms-page/infrastructure/cms-page-get-infra.ts

I want to merge this change because it fixes locale issue - it adds a fallback mechanism to attempt fetching cms data with default locale if the initial locale retrieval fails.
It also renames cms attributes.

Fix locale issue

---

apps/storefront/src/app/[locale]/(main)/_components/navigation.tsx
apps/storefront/src/components/footer/footer.tsx
apps/storefront/src/components/mobile-navigation.tsx
apps/storefront/src/lib/cms.ts
apps/storefront/src/lib/helpers.ts
apps/storefront/src/services/search.ts
packages/domain/src/objects/Menu.ts
packages/infrastructure/src/public/saleor/cms-menu/graphql/fragments/MenuItemFragment.graphql
packages/infrastructure/src/public/saleor/cms-menu/graphql/fragments/generated.ts
packages/infrastructure/src/public/saleor/cms-menu/graphql/queries/generated.ts
packages/infrastructure/src/public/saleor/cms-menu/infrastructure/cms-menu-get-infra.ts
packages/ui/src/components/navigation-menu.tsx

I want to merge this change because it adjust navigation:

feat: Adjust navigation

---

apps/storefront/src/app/[locale]/(main)/_components/navigation.tsx
apps/storefront/src/components/footer/footer.tsx
apps/storefront/src/components/header/mobile-side-menu.tsx
apps/storefront/src/components/mobile-navigation.tsx
apps/storefront/src/lib/helpers.ts
apps/storefront/src/services/cms.ts
packages/codegen/schema.ts
packages/domain/src/objects/Menu.ts
packages/infrastructure/src/lib/serializers/cms-menu.ts
packages/infrastructure/src/public/butter-cms/cms-menu/infrastructure/cms-menu-get-infra.ts
packages/infrastructure/src/public/saleor/cms-menu/graphql/fragments/MenuItemFragment.graphql
packages/infrastructure/src/public/saleor/cms-menu/graphql/fragments/generated.ts
packages/infrastructure/src/public/saleor/cms-menu/graphql/queries/generated.ts
packages/infrastructure/src/public/saleor/cms-menu/infrastructure/cms-menu-get-infra.ts
packages/ui/src/components/navigation-menu.tsx

I want to merge this change because it copies nav from fashion branch and refactores it.

refactor: Copy and refactor nav

---

apps/docs/.eslintrc.cjs
apps/docs/next-env.d.ts
apps/docs/next.config.mjs
apps/docs/package.json
apps/docs/pages/_app.tsx
apps/docs/pages/_meta.json
apps/docs/pages/_meta.ts
apps/docs/pages/quickstart/running-locally.mdx
apps/docs/theme.config.tsx
apps/docs/tsconfig.json
packages/eslint-config-custom/package.json
pnpm-lock.yaml

feat: Bump nextra to v3

---

apps/storefront/next.config.js
apps/storefront/package.json
apps/storefront/src/components/locale-switch/actions.ts
apps/storefront/src/i18n/routing.ts
apps/storefront/src/lib/paths.ts
apps/storefront/src/lib/types.ts
apps/storefront/src/middlewares/i18nMiddleware.ts
apps/storefront/src/regions/types.ts
pnpm-lock.yaml

The default locale is now "en-US" assigned to the storefront domain without locale prefix ("/"), all other supported locales are accessible under prefixed locale pathname ("e.g. "/gb").

feat: Set default locale without locale prefix in pathname

---

apps/storefront/src/i18n/routing.ts

This fixes the issue of unwanted redirects from `/` to the latest visited/saved locale e.g. `'/gb`.

fix: Disable localeDetection in next-intl routing config

---

apps/storefront/src/app/[locale]/(auth)/confirm-account-registration/page.tsx
apps/storefront/src/app/[locale]/(auth)/confirm-new-email/page.tsx
apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/delivery-method/page.tsx
apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/shipping-address/page.tsx
apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/user-details/page.tsx
apps/storefront/src/app/[locale]/(checkout)/checkout/page.tsx
apps/storefront/src/app/[locale]/(main)/account/privacy-settings/actions.ts
apps/storefront/src/app/[locale]/(main)/payment/confirmation/page.tsx
apps/storefront/src/app/[locale]/(main)/search/actions.ts
apps/storefront/src/components/account-menu/actions.ts
apps/storefront/src/components/header/actions.ts
apps/storefront/src/components/summary/side-summary.tsx
apps/storefront/src/i18n/routing.ts
apps/storefront/src/lib/checkout.ts

Because of disabling locale detection in next-intl routing config [here](https://github.com/mirumee/nimara-ecommerce/pull/111), we need to switch from using `redirect` function from `next-intl` instead of the default `next/navigation` to not to redirect to the wrong locale. 
Also, I'm adding back the types for `next-intl` `redirect` function export as it is still required for TypeScript.

fix: Use redirect function from next-intl instead from next/navigation

---

apps/storefront/src/app/[locale]/(main)/search/_listing/search-pagination.tsx

I want to merge this change because of the missing locale in pagination next and previous buttons.

fix: Pass locale explicitly to shadcn pagination links

---

packages/infrastructure/src/lib/serializers/cms-menu.ts

I want to merge this change because it fixes redirection on navbar links - when user click on collection using not default locale error pops up:
It can be caused by doubled slash in url.

fix: Fix wrong redirection on navbar links

---

apps/storefront/src/app/[locale]/(main)/search/actions.ts

I want to merge this change because it fixes clearing search params related to navigation. Before, if there were any search params related to navigation (e.g. category) and some related to filters while clearing all of them were cleared, even those not related to filters.

fix: Fix clearing search params

---

apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/payment/address-tab.tsx

I want to merge this change because it fixes the issue where an address was being saved as the default billing address, even when the checkbox was not checked and there are no saved addresses yet.

fix: Fix billing address behaviour when no addresses saved

---

packages/infrastructure/src/lib/serializers/cms-page.ts

I want to merge this change because previously, parseSaleorDataToFields assumed that field.values always contained at least one element.  
This caused a runtime error when field.values was undefined.
This fix ensures safe access to field.values[0] and properly filters the reference array,  
returning undefined instead of an empty array when no references exist.  
As a result, the function is now more robust and prevents potential crashes.

fix: prevent crash when field.values is undefined

---

apps/storefront/src/app/[locale]/(main)/_components/products-grid.tsx
apps/storefront/src/components/search-product-card.tsx

I want to merge this change because it ensures a consistent and visually appealing product grid layout on the /search page by limiting product names to two lines and enforcing a uniform image aspect ratio.

fix: inconsistent product grid on /search

---

apps/storefront/src/app/[locale]/(main)/_components/navigation.tsx

I want to merge this change because it fixes an issue where navbar items without children were incorrectly triggering menu state changes. This update ensures proper behavior by following the recommended approach from the shadcn documentation for handling navigation links.

fix(navigation): prevent unnecessary menu opening for non-dropdown items

---

apps/storefront/src/app/api/logout/route.ts

I want to merge this change because it fixes wrong redirection from email change confirmation link to `/sign-in` - now user confirming their email with `gb` locale is being redirected to `/gb/sign-in` page.

fix: Fix locale in sign-in redirection

---

apps/storefront/src/app/[locale]/(main)/search/_listing/search-sort-by.tsx

I want to merge this change because the previous touchend.preventDefault listener was preventing option selection on iPads and other touch devices.

fix(search): allow selecting options on touch devices by removing touched.preventDefault

---

apps/storefront/src/app/[locale]/(main)/products/[slug]/components/related-products.tsx

I want to merge this change because it ensures consistent sizing of product cards in the mobile carousel view. This removes unnecessary wrappers, uses Tailwind utilities correctly (e.g., w-4/5, flex-none), and improves readability and layout stability across breakpoints.

fix(PDP): adjust related products carousel for consistent layout on mobile

---

apps/storefront/src/app/[locale]/(main)/_components/search-pagination.tsx
apps/storefront/src/app/[locale]/(main)/search/actions.ts

I want to merge this change because this fixes an issue where changing filters while on a paginated results page would preserve outdated before or after cursors in the URL, leading to incorrect or inconsistent search results. By clearing pagination params (before, after) on every filter change, we ensure that search always starts from the first page with the correct filter context.

fix(search): clear pagination params on filter change to fix incorrect results

---

apps/storefront/src/middlewares/i18nMiddleware.test.ts
apps/storefront/src/middlewares/i18nMiddleware.ts

I want to merge this change because it ensures consistent locale redirect based on previously selected language from cookie - if user sets gb language, closes browser and opens in with root path, they are being redirected to /gb locale automatically.

feat: Ensure consistent locale redirect based on previously selected language

---

packages/infrastructure/src/search/saleor/infrastructure/search-infra.ts

I want to merge this change because it fixes a GraphQL error caused by passing both `filter` and `where` arguments to the product search query. With this update, the `where` clause is used exclusively when filtering by product IDs (e.g., for product carousels), and the `filter` object is applied otherwise — preserving support for attributes, categories, and collections filters. This makes the search logic more robust and compatible with Saleor's API constraints.

fix(search): avoid using both filter and where in search query

---

.github/workflows/release.yaml

I want to merge this change because it prevents from triggering a release job when someone will push the main branch in a forked repository.

fix: prevent running a release job in forked repositories
