mirumee/nimara-ecommerce

apps/storefront/src/components/header/mobile-search.tsx, apps/storefront/src/components/header/mobile-side-menu.tsx, apps/storefront/src/components/header/search-form.tsx, packages/ui/src/components/sheet.tsx
I want to merge this change because it improves search experience and it fixes minor issues related to search input.
=> fix: Improve search experience

apps/storefront/src/components/header/mobile-search.tsx, apps/storefront/src/components/header/mobile-side-menu.tsx, apps/storefront/src/components/header/search-form.tsx, packages/ui/src/components/sheet.tsx
I want to merge this change because it closes search form after submission on mobile.
=> fix: Close search form after submitting

apps/storefront/src/app/[locale]/(main)/account/addresses/page.tsx
I want to merge this change because it fixes doubled `Add new address` button on mobile.
=> fix: Remove doubled Add new address button

apps/storefront/messages/en-GB.json, apps/storefront/src/components/footer/footer.tsx
I want to merge this change because it adds small fixes / improvements to footer.
=> fix: Adjust footer

apps/storefront/src/components/header/search-form.tsx
I want to merge this change because it fixes closing search bar when it is clicked second and more time.
=> fix: Fix closing search bar

README.md
Changed movie file for better representation of the current store
Resolves:
NA
I want to merge this change because I was asked for update by marketing team. 
NA
=> chore: update demo movie in README.md

apps/automated-tests/pages/CheckoutPage.ts
This PR adds a check for saved payment methods by the user in checkout test scenarios.
=> fix: Check in e2e tests if user has saved payment methods

.github/workflows/release.yaml, apps/storefront/package.json, pnpm-lock.yaml
I want to merge this change to enable automated releases with GitHub Actions.
=> feat: Add semantic-release for automated releases

apps/storefront/src/app/[locale]/(main)/account/addresses/_modals/create-address-modal.tsx
I want to merge this change because of missing "Add new address button" in the account details page.
=> fix: Fix missing 'Add new address' button in account page

apps/storefront/src/app/[locale]/(main)/account/addresses/_modals/create-address-modal.tsx, apps/storefront/src/app/[locale]/(main)/account/addresses/page.tsx
This PR is fixing the problem with opening the add new address modal.
=> fix: Fix opening the add new address modal

apps/storefront/src/app/[locale]/(main)/search/page.tsx
I want to merge this change because it fixes search bar position - it reverts it to right when there is no header on search page.
=> fix: Fix search bar position

packages/infrastructure/src/lib/serializers/cms-menu.ts, packages/infrastructure/src/lib/serializers/cms-page.ts, packages/infrastructure/src/public/butter-cms/cms-menu/infrastructure/cms-menu-get-infra.ts, packages/infrastructure/src/public/butter-cms/cms-page/infrastructure/cms-page-get-infra.ts, packages/infrastructure/src/public/saleor/cms-menu/infrastructure/cms-menu-get-infra.ts, packages/infrastructure/src/public/saleor/cms-page/infrastructure/cms-page-get-infra.ts
I want to merge this change because it removes provider name from serializer functions.
=> Remove provider from serializer

apps/storefront/package.json, apps/storefront/src/app/[locale]/(main)/products/[slug]/components/variant-selector-utils.ts, apps/storefront/src/app/[locale]/(main)/products/[slug]/components/variant-selector.tsx, apps/storefront/src/app/[locale]/layout.tsx, pnpm-lock.yaml
I want to merge this change because I want to add Variant Selector With Swatch
=> Adjust storefront for fashion products

apps/storefront/src/config.ts
=> fix: Adjust cms cache

apps/storefront/src/components/header/search-form.tsx
=> [MS-840] bug fix search

apps/storefront/src/app/[locale]/(main)/search/page.tsx, apps/storefront/src/lib/cms.ts, packages/infrastructure/src/private/algolia/search/infrastructure/get-facets-infra.ts, packages/infrastructure/src/private/algolia/search/infrastructure/search-infra.ts
I want to merge this change because it allows to filter by collection.
=> feat: Add filtering by collection

apps/storefront/src/components/header/search-form.tsx
=> [MS-840] fix search with params

apps/storefront/src/components/header/search-form.tsx
=> [MS-840] fix search refresh bug

apps/storefront/next.config.js
I want to merge this change because robots.txt should not allow bots on dev, stage and any dev release.
=> fix: Disallow indexing if not production

apps/storefront/next.config.js, apps/storefront/package.json, pnpm-lock.yaml
This PR removes unused old region's config from next.config.ts.
=> chore: Remove regions' config in next.config.js

apps/storefront/src/app/[locale]/(main)/search/actions.ts
I want to merge this change because it fixes sorting on mobile.
=> fix: Fix sorting on mobile

apps/storefront/src/app/[locale]/(main)/layout.tsx, apps/storefront/src/lib/server.ts, packages/infrastructure/src/lib/serializers/cms-menu.ts, packages/infrastructure/src/public/saleor/cms-menu/infrastructure/cms-menu-get-infra.ts, packages/infrastructure/src/use-cases/cms-menu/types.ts
#135)I want to merge this change because it adds locale to menu item's relative path if needed.
=> fix: Fix locale in relative paths

apps/storefront/src/app/[locale]/(main)/account/orders/_forms/return-products-form.tsx
I want to merge this change because it fixes `Cancel` button behaviour on return modal. Previously, after selecting product to return and clicking `Cancel` button, mutation was being sent, now it works correctly.
=> fix: Fix return cancel button behaviour

apps/storefront/package.json, apps/storefront/src/app/[locale]/layout.tsx, pnpm-lock.yaml
I want to merge this change because it adds Vercel Speed Insights which provides detailed insights into Nimara's performance.
=> feat: Add Vercel Speed Insights

packages/ui/src/components/navigation-menu.tsx
I want to merge this change because it fixes issue related to menu which jitters when hovered.
=> fix: Fix jittering menu issue

apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/shipping-address/_forms/create-form.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/shipping-address/_tabs/address-tab.tsx
I want to merge this change because it fixes the issue where an address was being saved as the default shipping/billing address, even when the checkbox was not checked.
=> fix: Fix address checkbox behaviour

apps/storefront/next.config.js
I want to merge this change because it fixes indexing by search engines. If "Automatically expose System Environment Variables" is on we need to fetch "NEXT_PUBLIC_VERCEL_ENV" instead of just "VERCEL_ENV".
=> fix: Fix indexing by search engines

apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/payment/address-tab.tsx
I want to merge this change because it fixes the issue where an address was being saved as the default billing address, even when the checkbox was not checked.
=> fix: Fix billing address checkbox behaviour

apps/storefront/src/components/static-page/static-page.tsx
I want to merge this change because it adjusts static pages styles.
=> fix: Adjust static page style

apps/storefront/src/app/[locale]/(main)/_components/products-grid.tsx, apps/storefront/src/components/search-product-card.tsx
I want to merge this change because it adds a container that fixes the display of recommended products.
=> fix: add container for recommended products on the product page

apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/delivery-method/page.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/payment/page.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/shipping-address/page.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/actions.ts, apps/storefront/src/app/[locale]/(checkout)/checkout/page.tsx, apps/storefront/src/lib/checkout.ts
Resolves: 
- [MS-943](https://mirumee.atlassian.net/browse/MS-943)
[MS-943]: https://mirumee.atlassian.net/browse/MS-943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: checkout restrictions

apps/storefront/src/app/[locale]/(main)/_components/products-grid.tsx, apps/storefront/src/app/[locale]/(main)/page.tsx
=> fix(homepage): hide the products grid when no products have been added in the CMS [MS-961]

apps/storefront/messages/en-GB.json, apps/storefront/src/app/[locale]/(main)/_components/action.ts, apps/storefront/src/app/[locale]/(main)/_components/newsletter-form.tsx, apps/storefront/src/app/[locale]/(main)/_components/schema.ts, apps/storefront/src/app/[locale]/(main)/page.tsx
I want to merge this change because this PR lays the groundwork for the newsletter component. It includes the UI only, and we'll integrate it with a newsletter system in the next iteration.
=> feat(newsletter): prepare a newsletter component MS-955

apps/storefront/src/components/search-product-card.tsx, packages/infrastructure/src/config.ts
I want to merge this change because it improves the visual quality and consistency of product thumbnails on the PLP, especially on high-resolution screens, while maintaining good performance and responsiveness.
=> fix(search): improve thumbnail image quality and layout in product cards MS-942

apps/storefront/src/app/[locale]/(main)/cart/components/cart-details.tsx
I want to merge this change because it fixes API errors caused by multiply clicking on delete item from cart button - we now block all cart actions until the server confirms the cart update. The UI is only unblocked when the cart data is actually refreshed.
=> fix: Fix delete item from cart button behaviour

apps/storefront/messages/en-GB.json, apps/storefront/src/app/[locale]/(main)/collections/[slug]/opengraph-image.tsx, apps/storefront/src/app/[locale]/(main)/collections/[slug]/page.tsx, apps/storefront/src/app/[locale]/(main)/products/[slug]/page.tsx, apps/storefront/src/envs/client.ts
=> fix(PDP): fix product OG image MS-968

apps/storefront/src/app/[locale]/(main)/_components/newsletter-form.tsx, apps/storefront/src/app/[locale]/(main)/_components/schema.ts
I want to merge this change because it improves the user experience by properly validating the name field and ensuring consistent UI behavior.
=> fix(newsletter): UI display & schema for name MS-955

apps/storefront/src/app/[locale]/(checkout)/checkout/actions.ts
I want to merge this change because it fixes the checkout flow by ensuring that logged-in users can properly navigate through the checkout steps. This update allows users to stay on the "Shipping Address" and "Delivery Method" steps to edit details if needed, and ensures they are redirected to the appropriate step only when necessary (e.g. missing email, shipping address, or delivery method).
=> fix(checkout): fix checkout step redirection logic for logged-in users & allow editing of shipping address & delivery method

packages/infrastructure/src/public/stripe/payment/infrastructure/transaction-process-infra.ts, packages/infrastructure/src/public/stripe/payment/types.ts, packages/infrastructure/src/use-cases/payment/payment-result-process-use-case.ts
=> fix(checkout): return types of the transaction process and payment process MS-959

.vscode/settings.json, apps/storefront/src/app/[locale]/(auth)/create-account/actions.ts, apps/storefront/src/app/[locale]/(auth)/reset-password/action.ts, apps/storefront/src/app/[locale]/(main)/account/privacy-settings/actions.ts, apps/storefront/src/app/[locale]/(main)/account/profile/_forms/actions.ts, apps/storefront/src/auth.ts, apps/storefront/src/lib/actions/auth.ts, apps/storefront/src/lib/server.ts, packages/infrastructure/package.json, packages/infrastructure/src/public/saleor/auth/client.ts, pnpm-lock.yaml
I want to merge this change because it fixes `redirectionUrl` by fixing issue with slashes which caused omitting locale in url. It also updates Saleor auth client integration to support Next.js 15’s async cookies API and resolves several issues caused by the transition.
=> fix: Fix redirect paths

apps/storefront/src/app/[locale]/(auth)/confirm-new-email/page.tsx
I want to merge this change because it fixes message user sees after clicking again on email change confirmation link.
=> fix: Fix message when user clicks again on confirmation link

apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/payment/address-tab.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/shipping-address/_tabs/address-tab.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/_sections/shipping-address-section.tsx
I want to merge this change because it fixes inconsistent behavior when switching between editing and creating shipping addresses, ensuring that the correct country is applied in the form and address fields are rendered properly.
=> fix(ceckout): ensure correct country is selected in shipping address form MS-1003

apps/storefront/src/components/locale-switch/locale-modal.tsx
I want to merge this change because it fixes issue related to switch locale modal position when user scroll down the page.
=> fix: Fix locale modal position when page scrolled down

apps/storefront/messages/en-GB.json, apps/storefront/src/app/[locale]/(auth)/confirm-new-email/actions.ts, apps/storefront/src/app/[locale]/(auth)/confirm-new-email/page.tsx, apps/storefront/src/app/api/logout/route.ts, packages/domain/src/objects/Error.ts, packages/infrastructure/src/error.ts, packages/infrastructure/src/user/saleor/infrastructure/confirm-email-change-infra.ts
I want to merge this change because it fixes the emails related issue:
* user being redirected from email change confirmation link was able to directly change url from /sign-in to /account/profile and see empty user profile page;
* user after refreshing old session before email change was not redirected to /sign-in page;
* user after clicking again on email change confirmation link saw wrong error message.
=> fix: Fix emails related issues

apps/storefront/messages/en-GB.json, apps/storefront/src/app/[locale]/(main)/_components/hero-banner.tsx, apps/storefront/src/app/[locale]/(main)/_components/navigation.tsx, apps/storefront/src/app/[locale]/(main)/collections/[slug]/page.tsx, apps/storefront/src/app/[locale]/(main)/search/page.tsx, apps/storefront/src/components/header/logo.tsx, apps/storefront/src/components/locale-switch/locale-switch.tsx, apps/storefront/src/components/search-product-card.tsx
=> fix(SEO): improve HTML semantics for SEO MS-982

apps/storefront/src/app/[locale]/(main)/cart/components/cart-details.tsx
I want to merge this change because it fixes remove from cart button behavior - it was fixed before but after changes in infra issue appeared again.
=> fix: Fix remove button behavior

apps/storefront/messages/en-GB.json, apps/storefront/src/app/[locale]/(auth)/confirm-new-email/page.tsx, apps/storefront/src/app/[locale]/(main)/account/profile/_forms/update-email-form.tsx, apps/storefront/src/app/[locale]/(main)/account/profile/_modals/update-email-modal.tsx, apps/storefront/src/app/[locale]/(main)/account/profile/page.tsx, packages/domain/src/objects/Error.ts, packages/infrastructure/src/error.ts
I want to merge this change because it fixes error message for email change confirmation - it returns proper message when token is invalid or email has been already changed and it is used by user.
=> fix: Fix error message for email change confirmation

apps/storefront/src/app/[locale]/order/confirmation/[id]/actions.ts, apps/storefront/src/app/[locale]/order/confirmation/[id]/components/checkout-remover.tsx
=> fix(checkout): remove redirect from checkout remover MS-1016

apps/storefront/messages/en-GB.json, apps/storefront/src/app/[locale]/(main)/search/page.tsx
I want to merge this change because it updates the page title for the search view to better reflect its content.
=> fix(search): change the title of the search page

apps/storefront/src/app/[locale]/(auth)/create-account/form.tsx, apps/storefront/src/app/[locale]/(auth)/reset-password/form.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/user-details/form.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/(sign-in)/sign-in/page.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/_sections/delivery-method-section.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/_sections/email-section.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/_sections/shipping-address-section.tsx, apps/storefront/src/app/[locale]/(main)/_components/products-grid.tsx, apps/storefront/src/app/[locale]/(main)/account/addresses/_modals/update-address-modal.tsx, apps/storefront/src/app/[locale]/(main)/account/payment-methods/components/payment-method-delete-modal.tsx, apps/storefront/src/app/[locale]/(main)/account/profile/_forms/update-email-form.tsx, apps/storefront/src/app/[locale]/(main)/account/profile/_forms/update-name-form.tsx, apps/storefront/src/app/[locale]/(main)/account/profile/_forms/update-password-form.tsx, apps/storefront/src/app/[locale]/(main)/cart/components/cart-details.tsx, apps/storefront/src/app/[locale]/(main)/products/[slug]/components/add-to-bag.tsx, apps/storefront/src/components/account-menu/side-links.tsx, apps/storefront/src/components/header/mobile-search.tsx, apps/storefront/src/components/header/mobile-side-menu.tsx, apps/storefront/src/components/header/shopping-bag-icon.tsx, apps/storefront/src/components/locale-switch/locale-modal.tsx, apps/storefront/src/components/shopping-bag/components/line.tsx, packages/ui/src/components/input.tsx
I want to merge this change because it improves visual consistency across the app by unifying icon button padding and aligning our usage of the Button component. This makes the UI more polished and the codebase easier to maintain.
=> refactor(button): fix icon button spacing & unify usage patterns

packages/infrastructure/src/search/saleor/infrastructure/search-infra.ts
I want to merge this change because it fixes a bug where applying filters (e.g. category) would override the search query. The logic now prioritizes full-text search when a query is present, while still allowing category and collection filters to work when no query is used. Results are sourced dynamically from the appropriate GraphQL field depending on the context.
=> fix(search): ensure search text works alongside filters

apps/storefront/src/app/[locale]/(auth)/reset-password/action.ts
I want to merge this change because it fixes password recovery process by redirecting to proper url (new-password page).
=> fix: Pass proper redirection link

apps/storefront/messages/en-GB.json, apps/storefront/package.json, apps/storefront/src/app/[locale]/(main)/payment/confirmation/page.tsx, apps/storefront/src/app/api/logout/route.ts, apps/storefront/src/components/locale-switch/actions.ts, apps/storefront/src/config.ts, apps/storefront/src/i18n/routing.ts, apps/storefront/src/lib/test/mock.ts, apps/storefront/src/lib/test/setup.ts, apps/storefront/src/middlewares/i18nMiddleware.test.ts, apps/storefront/src/middlewares/i18nMiddleware.ts, apps/storefront/vitest.config.ts, package.json, pnpm-lock.yaml
=> fix(checkout): remove checkoutId cookie on locale change

apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/payment/address-tab.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/payment/payment.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/shipping-address/_forms/create-form.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/shipping-address/_forms/guest-form.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/shipping-address/_forms/update-form.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/shipping-address/_tabs/address-tab.tsx, apps/storefront/src/app/[locale]/(main)/account/addresses/_forms/create-address-form.tsx, apps/storefront/src/app/[locale]/(main)/account/addresses/_forms/update-address-form.tsx, apps/storefront/src/app/[locale]/(main)/account/addresses/_modals/update-address-modal.tsx, apps/storefront/src/app/[locale]/(main)/account/addresses/page.tsx, apps/storefront/src/components/address-form/address-form.tsx
I want to merge this change because it fixes the problem where the address form was stuck on "Changing country..." after selecting a new country.
=> fix(checkout): address form hang on country change by relying on dynamic fields load state MS-1041

apps/storefront/src/app/[locale]/(main)/_components/navigation.tsx, apps/storefront/src/components/footer/footer.tsx, apps/storefront/src/middleware.ts, apps/storefront/src/middlewares/i18nMiddleware.ts
=> fix(checkout): disable prefetch in nav/footer to keep the checkoutId

apps/storefront/src/middleware.ts
I want to merge this change because it fixes the 404 for email files.
=> fix: middleware matcher - 404 for static files

apps/storefront/messages/en-GB.json, apps/storefront/src/app/[locale]/(main)/_components/breadcrumbs.tsx, apps/storefront/src/app/[locale]/(main)/collections/[slug]/page.tsx, apps/storefront/src/app/[locale]/(main)/products/[slug]/components/product-details-container.tsx, apps/storefront/src/app/[locale]/(main)/search/page.tsx, packages/domain/src/objects/Product.ts, packages/infrastructure/src/store/saleor/graphql/fragments/ProductBaseFragment.graphql, packages/infrastructure/src/store/saleor/graphql/fragments/generated.ts, packages/infrastructure/src/store/saleor/graphql/queries/generated.ts, packages/infrastructure/src/store/saleor/infrastructure/get-product-base-infra.ts, packages/infrastructure/src/store/saleor/infrastructure/get-product-details-infra.ts, packages/ui/src/components/breadcrumb.tsx
I want to merge this change because it introduces a reusable Breadcrumbs component for consistent navigation across pages.
=> feat: add breadcrumbs navigation MS-1004

apps/storefront/messages/en-GB.json, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/delivery-method/page.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/payment/page.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/shipping-address/page.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/user-details/page.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/page.tsx, apps/storefront/src/app/[locale]/(main)/cart/components/cart-details.tsx, apps/storefront/src/app/[locale]/(main)/products/[slug]/_actions/add-to-bag.ts, apps/storefront/src/components/shopping-bag/components/lines.tsx, apps/storefront/src/components/summary/summary.tsx, apps/storefront/src/config.ts, apps/storefront/src/lib/actions/cart.ts, apps/storefront/src/lib/checkout.ts, apps/storefront/src/lib/formatters/util.ts, packages/domain/src/objects/Cart.ts, packages/domain/src/objects/Checkout.ts, packages/infrastructure/src/auth/saleor/infrastructure/token-refresh-infra.ts, packages/infrastructure/src/cart/saleor/graphql/fragments/CartFragment.graphql, packages/infrastructure/src/cart/saleor/graphql/fragments/generated.ts, packages/infrastructure/src/cart/saleor/graphql/queries/generated.ts, packages/infrastructure/src/cart/saleor/infrastructure/cart-get-infra.ts, packages/infrastructure/src/checkout/saleor/graphql/fragments/CheckoutFragment.graphql, packages/infrastructure/src/checkout/saleor/graphql/fragments/CheckoutProblemsFragment.graphql, packages/infrastructure/src/checkout/saleor/graphql/fragments/generated.ts, packages/infrastructure/src/checkout/saleor/graphql/queries/generated.ts, packages/infrastructure/src/checkout/saleor/infrastructure/checkout-get-infra.ts, packages/infrastructure/src/checkout/saleor/serializers.ts
I want to merge this change because it improves the error handling for unavailable items in the cart/checkout
[MS-742](https://mirumee.atlassian.net/browse/MS-742)
[MS-742]: https://mirumee.atlassian.net/browse/MS-742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(checkout): improve error handling for unavailable items in the cart/checkout - MS-742

packages/infrastructure/src/address/saleor/infrastructure/countries-all-get-infra.ts
I want to merge this change because it removes the EU from the list of countries as it's not a valid country.
- [MS-1066](https://mirumee.atlassian.net/issues/MS-1066)
[MS-1066]: https://mirumee.atlassian.net/browse/MS-1066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(account): remove EU from the list of all countries - MS-1066

packages/ui/src/components/multi-select.tsx, packages/ui/src/components/select.tsx
=> fix: improve UI of the multiselect component - MS-1011

apps/storefront/src/components/footer/footer.tsx, apps/storefront/src/components/header/header.tsx
I want to merge this change because it fixes logo and footer links click area - only svg and link text are clickable.
=> fix: Adjust logo and footer link click area

apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/shipping-address/_forms/actions.ts, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/shipping-address/_forms/create-form.tsx, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/shipping-address/_forms/schema.ts, apps/storefront/src/app/[locale]/(checkout)/checkout/(checkout-details)/shipping-address/_forms/update-form.tsx
This PR separates shipping address schema into two schemas: Update and Create with one additional field
=> fix(checkout): fix hidden form errors while editing a shipping address - MS-1069

.env.example, apps/docs/app/quickstart/environment-variables/page.mdx, apps/storefront/src/app/[locale]/(main)/collections/[slug]/opengraph-image.tsx, apps/storefront/src/app/[locale]/(main)/products/[slug]/opengraph-image.tsx, apps/storefront/src/app/[locale]/(main)/search/page.tsx, apps/storefront/src/app/robots.ts, apps/storefront/src/app/sitemap.ts, apps/storefront/src/envs/client.ts, packages/infrastructure/src/address/saleor/address-form/parse-address-form-rows.ts, packages/infrastructure/src/collection/saleor/infrastructure/get-collections-ids-by-slugs-infra.ts, packages/infrastructure/src/logging/service.ts, turbo.json
I want to merge this change because it fixes a few things that came up when we were deploying a storefront for saleor.
=> fix: saleor deployment feedback fixes

apps/docs/app/quickstart/stripe-integration/page.mdx
I want to merge this change because it updates Stripe docs.
=> docs:  Update Stripe docs

apps/storefront/src/components/header/header.tsx, apps/storefront/src/components/header/mobile-side-menu.tsx
I want to merge this change because it fixes:
=> fix: Render shopping bag icon correctly on mobile

apps/storefront/src/app/[locale]/(auth)/new-password/form.tsx, apps/storefront/src/app/[locale]/(auth)/reset-password/reset-password-form.tsx, apps/storefront/src/app/[locale]/(main)/account/addresses/_modals/update-address-modal.tsx, apps/storefront/src/app/[locale]/(main)/account/layout.tsx, apps/storefront/src/app/[locale]/(main)/account/payment-methods/components/add-new-payment-trigger.tsx, apps/storefront/src/app/[locale]/(main)/account/payment-methods/components/payment-method-delete-modal.tsx, apps/storefront/src/app/[locale]/(main)/account/payment-methods/components/payment-methods-list.tsx, apps/storefront/src/app/[locale]/(main)/account/payment-methods/page.tsx, apps/storefront/src/app/[locale]/(main)/collections/[slug]/page.tsx, apps/storefront/src/app/[locale]/(main)/search/_filters/color-swatch.tsx, apps/storefront/src/app/[locale]/(main)/search/_filters/filter-boolean.tsx, apps/storefront/src/app/[locale]/(main)/search/_filters/filter-text.tsx, apps/storefront/src/app/[locale]/(main)/search/_filters/filters-container.tsx, apps/storefront/src/app/[locale]/layout.tsx, apps/storefront/src/components/mobile-navigation.tsx, apps/storefront/src/components/search-product-card.tsx, apps/storefront/src/lib/scripts/theme-preload-script.ts, apps/storefront/src/providers/theme-provider.tsx, packages/ui/src/components/input.tsx, packages/ui/src/components/rich-text/editorjs-renderer.tsx, packages/ui/src/components/rich-text/html-renderer.tsx, packages/ui/src/components/rich-text/markdown-renderer.tsx, packages/ui/src/components/select.tsx, packages/ui/src/styles/globals.css
I want to merge this change because it fixes dark mode issues.
=> feat: Fix dark mode issues

apps/docs/app/quickstart/_meta.ts, apps/docs/app/quickstart/add-new-channel/page.mdx
I want to merge this change because it adds docs for setting up new channel in Nimara.
=> feat(docs): Add docs for setting up new channel

apps/storefront/src/regions/config.ts, apps/storefront/src/regions/types.ts, apps/storefront/src/regions/utils.ts
I want to merge this change because it adds support for default channel in Saleor improving compatibility between fresh Saleor instance and Nimara. User which does not have custom channel created is able to fetch data from `default-channel`.
=> feat: Add support for Saleor default channel

apps/storefront/src/app/[locale]/(main)/account/addresses/_modals/create-address-modal.tsx, apps/storefront/src/app/[locale]/(main)/account/addresses/page.tsx
I want to merge this change because it fixes Add new address modal - children of DialogTrigger should be passed as a single React child.
=> fix: Fix Add new address modal

apps/storefront/src/components/static-page/static-page.tsx
I want to merge this change because it fixes long text on static pages - long words were unbreakable and disrupted layout on mobile view.
=> fix: Fix long texts on static pages

apps/storefront/src/app/[locale]/(main)/_components/navigation.tsx
I want to merge this change because it removes deprecated `fill` prop from Image component.
=> fix: Remove deprecated layout prop

apps/storefront/src/components/shopping-bag/components/line.tsx, packages/domain/src/objects/common.ts, packages/infrastructure/src/cart/saleor/graphql/fragments/generated.ts, packages/infrastructure/src/cart/saleor/graphql/queries/generated.ts, packages/infrastructure/src/checkout/saleor/graphql/fragments/generated.ts, packages/infrastructure/src/checkout/saleor/graphql/queries/generated.ts, packages/infrastructure/src/graphql/fragments/CartLineFragment.graphql, packages/infrastructure/src/graphql/fragments/generated.ts, packages/infrastructure/src/utils.ts
I want to merge this change because it adds attributes in cart line name which makes product line distinguishable:
=> feat: Add attributes in cart line name

apps/storefront/src/app/api/acp/[channelSlug]/product_feed/route.ts, packages/infrastructure/package.json, packages/infrastructure/src/mcp/saleor/infrastructure/get-product-feed.ts, packages/infrastructure/src/mcp/saleor/serializers.ts, packages/infrastructure/src/mcp/saleor/service.ts, packages/infrastructure/src/mcp/schema.ts, packages/infrastructure/src/mcp/types.ts, pnpm-lock.yaml
=> add product feed infra
